idf_component_register(SRC_DIRS "."
                       INCLUDE_DIRS "."
                       REQUIRES
                       bsp
                       display
                       touch
                       gui
                       wifi
                       ethernet
                       nvs_flash
                       )
